// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudyHub.DAL.Persistence;

#nullable disable

namespace StudyHub.DAL.Migrations
{
    [DbContext(typeof(StudyHubDbContext))]
    partial class StudyHubDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("Latin1_General_100_CI_AS_SC")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StudyHub.DAL.Entities.AcademicTerm", b =>
                {
                    b.Property<long>("AcademicTermId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AcademicTermId"));

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("TermName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("AcademicTermId");

                    b.HasIndex(new[] { "UserId", "TermName" }, "UQ_AcademicTerms_Name")
                        .IsUnique();

                    b.HasIndex(new[] { "AcademicTermId", "UserId" }, "UQ_AcademicTerms_Owner")
                        .IsUnique();

                    b.ToTable("AcademicTerms");
                });

            modelBuilder.Entity("StudyHub.DAL.Entities.ActivityEvent", b =>
                {
                    b.Property<long>("ActivityEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ActivityEventId"));

                    b.Property<DateOnly>("ActivityDate")
                        .HasColumnType("date");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)");

                    b.Property<bool?>("IsStudyAction")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bit")
                        .HasComputedColumnSql("(CONVERT([bit],case when [EventType]='DeadlineCompleted' OR [EventType]='FocusCompleted' OR [EventType]='FlashcardReviewed' OR [EventType]='NoteSaved' then (1) else (0) end))", true);

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("ActivityEventId");

                    b.HasIndex(new[] { "OccurredAtUtc", "UserId" }, "IX_ActivityEvents_Analytics");

                    b.HasIndex(new[] { "UserId", "ActivityDate", "IsStudyAction" }, "IX_ActivityEvents_Streak");

                    b.HasIndex(new[] { "RequestId" }, "UQ_ActivityEvents_Request")
                        .IsUnique();

                    b.ToTable("ActivityEvents");
                });

            modelBuilder.Entity("StudyHub.DAL.Entities.AuditLog", b =>
                {
                    b.Property<long>("AuditLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AuditLogId"));

                    b.Property<string>("ActionCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<long?>("ActorUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("EntityKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Summary")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("AuditLogId");

                    b.HasIndex("ActorUserId");

                    b.HasIndex(new[] { "CreatedAtUtc" }, "IX_AuditLogs_Date")
                        .IsDescending();

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("StudyHub.DAL.Entities.ContentReport", b =>
                {
                    b.Property<long>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ReportId"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<long?>("DeckId")
                        .HasColumnType("bigint");

                    b.Property<long?>("DocumentId")
                        .HasColumnType("bigint");

                    b.Property<long?>("GroupPostId")
                        .HasColumnType("bigint");

                    b.Property<long?>("NoteId")
                        .HasColumnType("bigint");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<long>("ReporterUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("ResolutionNote")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("ResolvedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<long?>("ResolvedByUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasDefaultValue("Open");

                    b.HasKey("ReportId");

                    b.HasIndex("DeckId");

                    b.HasIndex("DocumentId");

                    b.HasIndex("GroupPostId");

                    b.HasIndex("NoteId");

                    b.HasIndex("ReporterUserId");

                    b.HasIndex("ResolvedByUserId");

                    b.HasIndex(new[] { "Status", "CreatedAtUtc" }, "IX_ContentReports_Queue");

                    b.ToTable("ContentReports");
                });

            modelBuilder.Entity("StudyHub.DAL.Entities.Deadline", b =>
                {
                    b.Property<long>("DeadlineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("DeadlineId"));

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("DueAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<byte>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)2);

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasDefaultValue("Pending");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UserSubjectId")
                        .HasColumnType("bigint");

                    b.HasKey("DeadlineId");

                    b.HasIndex("UserSubjectId", "UserId");

                    b.HasIndex(new[] { "UserId", "IsDeleted", "Status", "DueAtUtc" }, "IX_Deadlines_Due");

                    b.HasIndex(new[] { "DeadlineId", "UserId" }, "UQ_Deadlines_Owner")
                        .IsUnique();

                    b.ToTable("Deadlines");
                });

            modelBuilder.Entity("StudyHub.DAL.Entities.Document", b =>
                {
                    b.Property<long>("DocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("DocumentId"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ExternalUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<long?>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MimeType")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("OriginalFileName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("OwnerUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("StorageKey")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<long?>("StudyGroupId")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<long?>("UserSubjectId")
                        .HasColumnType("bigint");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasDefaultValue("Private");

                    b.HasKey("DocumentId");

                    b.HasIndex("UserSubjectId", "OwnerUserId");

                    b.HasIndex(new[] { "StudyGroupId", "Visibility", "IsDeleted" }, "IX_Documents_Group");

                    b.HasIndex(new[] { "OwnerUserId", "IsDeleted", "CreatedAtUtc" }, "IX_Documents_Owner")
                        .IsDescending(false, false, true);

                    b.HasIndex(new[] { "UserSubjectId", "Visibility", "IsDeleted" }, "IX_Documents_Subject");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("StudyHub.DAL.Entities.DocumentBookmark", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long>("DocumentId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.HasKey("UserId", "DocumentId");

                    b.HasIndex("DocumentId");

                    b.ToTable("DocumentBookmarks");
                });

            modelBuilder.Entity("StudyHub.DAL.Entities.ExternalLogin", b =>
                {
                    b.Property<string>("Provider")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("ProviderSubject")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<DateTime?>("LastLoginAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Provider", "ProviderSubject");

                    b.HasIndex(new[] { "UserId", "Provider" }, "UQ_ExternalLogins_UserProvider")
                        .IsUnique();

                    b.ToTable("ExternalLogins", t =>
                        {
                            t.HasCheckConstraint("CK_ExternalLogins_Provider", "[Provider] IN ('Google', 'Development')");
                        });
                });

            modelBuilder.Entity("StudyHub.DAL.Entities.Flashcard", b =>
                {
                    b.Property<long>("FlashcardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("FlashcardId"));

                    b.Property<string>("BackText")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<long>("DeckId")
                        .HasColumnType("bigint");

                    b.Property<string>("FrontText")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.HasKey("FlashcardId");

                    b.HasIndex(new[] { "DeckId", "IsDeleted", "SortOrder" }, "IX_Flashcards_Deck");

                    b.ToTable("Flashcards");
                });

            modelBuilder.Entity("StudyHub.DAL.Entities.FlashcardDeck", b =>
                {
                    b.Property<long>("DeckId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("DeckId"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<long>("OwnerUserId")
                        .HasColumnType("bigint");

                    b.Property<long?>("StudyGroupId")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<long?>("UserSubjectId")
                        .HasColumnType("bigint");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasDefaultValue("Private");

                    b.HasKey("DeckId");

                    b.HasIndex("UserSubjectId", "OwnerUserId");

                    b.HasIndex(new[] { "StudyGroupId", "Visibility", "IsDeleted" }, "IX_FlashcardDecks_Group");

                    b.HasIndex(new[] { "OwnerUserId", "IsDeleted" }, "IX_FlashcardDecks_Owner");

                    b.ToTable("FlashcardDecks");
                });

            modelBuilder.Entity("StudyHub.DAL.Entities.FlashcardProgress", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long>("FlashcardId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("EaseFactor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(4, 2)")
                        .HasDefaultValue(2.50m);

                    b.Property<int>("IntervalDays")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastReviewedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("NextReviewAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int>("RepetitionCount")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("UserId", "FlashcardId");

                    b.HasIndex("FlashcardId");

                    b.HasIndex(new[] { "UserId", "NextReviewAtUtc" }, "IX_FlashcardProgress_Due");

                    b.ToTable("FlashcardProgress", (string)null);
                });

            modelBuilder.Entity("StudyHub.DAL.Entities.FlashcardReview", b =>
                {
                    b.Property<long>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ReviewId"));

                    b.Property<long>("FlashcardId")
                        .HasColumnType("bigint");

                    b.Property<byte>("Rating")
                        .HasColumnType("tinyint");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("ResponseMilliseconds")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReviewedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("ReviewId");

                    b.HasIndex("UserId", "FlashcardId");

                    b.HasIndex(new[] { "UserId", "ReviewedAtUtc" }, "IX_FlashcardReviews_History")
                        .IsDescending(false, true);

                    b.HasIndex(new[] { "RequestId" }, "UQ_FlashcardReviews_Request")
                        .IsUnique();

                    b.ToTable("FlashcardReviews");
                });

            modelBuilder.Entity("StudyHub.DAL.Entities.Goal", b =>
                {
                    b.Property<long>("GoalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("GoalId"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<decimal>("CurrentValue")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<decimal>("TargetValue")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UnitCode")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UserSubjectId")
                        .HasColumnType("bigint");

                    b.HasKey("GoalId");

                    b.HasIndex("UserSubjectId", "UserId");

                    b.HasIndex(new[] { "UserId", "IsCancelled", "EndDate" }, "IX_Goals_User");

                    b.ToTable("Goals");
                });

            modelBuilder.Entity("StudyHub.DAL.Entities.GradeEntry", b =>
                {
                    b.Property<long>("GradeEntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("GradeEntryId"));

                    b.Property<DateOnly>("AssessedOn")
                        .HasColumnType("date");

                    b.Property<string>("AssessmentType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Other");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("MaxScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(8, 2)")
                        .HasDefaultValue(10m);

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<decimal>("Score")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<long>("UserSubjectId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Weight")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(6, 2)")
                        .HasDefaultValue(1m);

                    b.HasKey("GradeEntryId");

                    b.HasIndex(new[] { "UserSubjectId", "IsDeleted" }, "IX_GradeEntries_Subject");

                    b.ToTable("GradeEntries");
                });

            modelBuilder.Entity("StudyHub.DAL.Entities.GroupInvite", b =>
                {
                    b.Property<string>("InviteCode")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<long>("CreatedByUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<int>("MaxUses")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(20);

                    b.Property<long>("StudyGroupId")
                        .HasColumnType("bigint");

                    b.Property<int>("UseCount")
                        .HasColumnType("int");

                    b.HasKey("InviteCode");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex(new[] { "StudyGroupId", "IsRevoked", "ExpiresAtUtc" }, "IX_GroupInvites_Group");

                    b.ToTable("GroupInvites");
                });

            modelBuilder.Entity("StudyHub.DAL.Entities.GroupMember", b =>
                {
                    b.Property<long>("StudyGroupId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("JoinedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("MemberRole")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasDefaultValue("Member");

                    b.Property<DateTime>("RequestedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasDefaultValue("Pending");

                    b.HasKey("StudyGroupId", "UserId");

                    b.HasIndex(new[] { "UserId", "Status", "StudyGroupId" }, "IX_GroupMembers_User");

                    b.ToTable("GroupMembers");
                });

            modelBuilder.Entity("StudyHub.DAL.Entities.GroupPost", b =>
                {
                    b.Property<long>("GroupPostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("GroupPostId"));

                    b.Property<long>("AuthorUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPinned")
                        .HasColumnType("bit");

                    b.Property<string>("PostType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasDefaultValue("Message");

                    b.Property<long>("StudyGroupId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.HasKey("GroupPostId");

                    b.HasIndex("StudyGroupId", "AuthorUserId");

                    b.HasIndex(new[] { "StudyGroupId", "IsDeleted", "CreatedAtUtc" }, "IX_GroupPosts_Feed")
                        .IsDescending(false, false, true);

                    b.ToTable("GroupPosts");
                });

            modelBuilder.Entity("StudyHub.DAL.Entities.Note", b =>
                {
                    b.Property<long>("NoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("NoteId"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("");

                    b.Property<string>("BodyFormat")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasDefaultValue("Markdown");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPinned")
                        .HasColumnType("bit");

                    b.Property<long>("OwnerUserId")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<long?>("StudyGroupId")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<long?>("UserSubjectId")
                        .HasColumnType("bigint");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasDefaultValue("Private");

                    b.HasKey("NoteId");

                    b.HasIndex("UserSubjectId", "OwnerUserId");

                    b.HasIndex(new[] { "StudyGroupId", "Visibility", "IsDeleted" }, "IX_Notes_Group");

                    b.HasIndex(new[] { "OwnerUserId", "IsDeleted", "UpdatedAtUtc" }, "IX_Notes_Owner")
                        .IsDescending(false, false, true);

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("StudyHub.DAL.Entities.Reminder", b =>
                {
                    b.Property<long>("ReminderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ReminderId"));

                    b.Property<string>("Channel")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasDefaultValue("InApp");

                    b.Property<long?>("DeadlineId")
                        .HasColumnType("bigint");

                    b.Property<string>("LastError")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateOnly?>("OccurrenceDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("RemindAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<long?>("ScheduleEventId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("SentAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasDefaultValue("Pending");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("ReminderId");

                    b.HasIndex("DeadlineId", "UserId");

                    b.HasIndex("ScheduleEventId", "UserId");

                    b.HasIndex(new[] { "Status", "RemindAtUtc" }, "IX_Reminders_Queue");

                    b.HasIndex(new[] { "UserId", "DeadlineId", "Channel", "RemindAtUtc" }, "UX_Reminders_Deadline")
                        .IsUnique()
                        .HasFilter("([DeadlineId] IS NOT NULL)");

                    b.HasIndex(new[] { "UserId", "ScheduleEventId", "OccurrenceDate", "Channel", "RemindAtUtc" }, "UX_Reminders_Event")
                        .IsUnique()
                        .HasFilter("([ScheduleEventId] IS NOT NULL)");

                    b.ToTable("Reminders");
                });

            modelBuilder.Entity("StudyHub.DAL.Entities.ScheduleEvent", b =>
                {
                    b.Property<long>("ScheduleEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ScheduleEventId"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("EndAtLocal")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasDefaultValue("Class");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("RepeatMode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasDefaultValue("None");

                    b.Property<DateOnly?>("RepeatUntilDate")
                        .HasColumnType("date");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("StartAtLocal")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("SE Asia Standard Time");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UserSubjectId")
                        .HasColumnType("bigint");

                    b.HasKey("ScheduleEventId");

                    b.HasIndex("UserSubjectId", "UserId");

                    b.HasIndex(new[] { "UserId", "IsDeleted", "StartAtLocal" }, "IX_ScheduleEvents_Calendar");

                    b.HasIndex(new[] { "ScheduleEventId", "UserId" }, "UQ_ScheduleEvents_Owner")
                        .IsUnique();

                    b.ToTable("ScheduleEvents");
                });

            modelBuilder.Entity("StudyHub.DAL.Entities.ScheduleException", b =>
                {
                    b.Property<long>("ScheduleEventId")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("OccurrenceDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("NewEndAtLocal")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("NewLocation")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("NewStartAtLocal")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.HasKey("ScheduleEventId", "OccurrenceDate");

                    b.ToTable("ScheduleExceptions");
                });

            modelBuilder.Entity("StudyHub.DAL.Entities.StudyGroup", b =>
                {
                    b.Property<long>("StudyGroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("StudyGroupId"));

                    b.Property<string>("ContactUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Goal")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<string>("JoinMode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasDefaultValue("Approval");

                    b.Property<short>("MaxMembers")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)20);

                    b.Property<string>("MeetingFormat")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasDefaultValue("Online");

                    b.Property<string>("MeetingSchedule")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<long>("OwnerUserId")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Rules")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int?>("SubjectId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasDefaultValue("Private");

                    b.HasKey("StudyGroupId");

                    b.HasIndex("OwnerUserId");

                    b.HasIndex("SubjectId");

                    b.ToTable("StudyGroups");
                });

            modelBuilder.Entity("StudyHub.DAL.Entities.StudySession", b =>
                {
                    b.Property<long>("StudySessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("StudySessionId"));

                    b.Property<DateTime?>("EndedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<int>("FocusSeconds")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasDefaultValue("Running");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UserSubjectId")
                        .HasColumnType("bigint");

                    b.HasKey("StudySessionId");

                    b.HasIndex("UserSubjectId", "UserId");

                    b.HasIndex(new[] { "UserId", "StartedAtUtc" }, "IX_StudySessions_User")
                        .IsDescending(false, true);

                    b.HasIndex(new[] { "UserId" }, "UX_StudySessions_Running")
                        .IsUnique()
                        .HasFilter("([Status]='Running')");

                    b.ToTable("StudySessions");
                });

            modelBuilder.Entity("StudyHub.DAL.Entities.Subject", b =>
                {
                    b.Property<int>("SubjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubjectId"));

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("SubjectCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("SubjectId");

                    b.HasIndex(new[] { "SubjectCode" }, "UQ_Subjects_Code")
                        .IsUnique();

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("StudyHub.DAL.Entities.SystemSetting", b =>
                {
                    b.Property<string>("SettingKey")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SettingValue")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<long?>("UpdatedByUserId")
                        .HasColumnType("bigint");

                    b.HasKey("SettingKey");

                    b.HasIndex("UpdatedByUserId");

                    b.ToTable("SystemSettings");
                });

            modelBuilder.Entity("StudyHub.DAL.Entities.User", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("UserId"));

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("ClassName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EducationLevel")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("University");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("RoleCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Student");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SchoolName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Active");

                    b.Property<string>("StudentCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.HasKey("UserId");

                    b.HasIndex(new[] { "Email" }, "IX_Users_Email");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("StudyHub.DAL.Entities.UserSetting", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<short>("DailyStudyGoalMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)30);

                    b.Property<short>("DefaultReminderMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)15);

                    b.Property<bool>("EmailRemindersEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("InAppRemindersEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasDefaultValue("vi");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasDefaultValue("System");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("SE Asia Standard Time");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.HasKey("UserId");

                    b.ToTable("UserSettings");
                });

            modelBuilder.Entity("StudyHub.DAL.Entities.UserSubject", b =>
                {
                    b.Property<long>("UserSubjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("UserSubjectId"));

                    b.Property<long>("AcademicTermId")
                        .HasColumnType("bigint");

                    b.Property<string>("ClassCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ColorHex")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(7)
                        .IsUnicode(false)
                        .HasColumnType("char(7)")
                        .HasDefaultValue("#5138EE")
                        .IsFixedLength();

                    b.Property<decimal>("CreditWeight")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5, 2)")
                        .HasDefaultValue(1m);

                    b.Property<string>("CustomSubjectName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<int?>("SubjectId")
                        .HasColumnType("int");

                    b.Property<decimal?>("TargetScore10")
                        .HasColumnType("decimal(4, 2)");

                    b.Property<string>("TeacherName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("UserSubjectId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("AcademicTermId", "UserId");

                    b.HasIndex(new[] { "UserId", "AcademicTermId", "SubjectId" }, "UQ_UserSubjects_CatalogEnrollment")
                        .IsUnique()
                        .HasFilter("[SubjectId] IS NOT NULL AND [IsArchived] = 0");

                    b.HasIndex(new[] { "UserId", "AcademicTermId", "CustomSubjectName" }, "UQ_UserSubjects_CustomEnrollment")
                        .IsUnique()
                        .HasFilter("[CustomSubjectName] IS NOT NULL AND [IsArchived] = 0");

                    b.HasIndex(new[] { "UserSubjectId", "UserId" }, "UQ_UserSubjects_Owner")
                        .IsUnique();

                    b.ToTable("UserSubjects", t =>
                        {
                            t.HasCheckConstraint("CK_UserSubjects_SubjectOrCustom", "([SubjectId] IS NOT NULL AND [CustomSubjectName] IS NULL) OR ([SubjectId] IS NULL AND [CustomSubjectName] IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("StudyHub.DAL.Entities.VwDailyUsageUtc", b =>
                {
                    b.Property<int?>("ActiveLearners")
                        .HasColumnType("int");

                    b.Property<int?>("ActiveUsers")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("ActivityDateUtc")
                        .HasColumnType("date");

                    b.Property<long?>("EventCount")
                        .HasColumnType("bigint");

                    b.ToTable((string)null);

                    b.ToView("vw_DailyUsageUtc", (string)null);
                });

            modelBuilder.Entity("StudyHub.DAL.Entities.VwStudyStreak", b =>
                {
                    b.Property<int?>("CurrentStreakDays")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("LastStudyDate")
                        .HasColumnType("date");

                    b.Property<int?>("LongestStreakDays")
                        .HasColumnType("int");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.ToTable((string)null);

                    b.ToView("vw_StudyStreaks", (string)null);
                });

            modelBuilder.Entity("StudyHub.DAL.Entities.VwSubjectGradeSummary", b =>
                {
                    b.Property<long>("AcademicTermId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("CreditWeight")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal?>("CurrentAverage10")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<int?>("EnteredAssessmentCount")
                        .HasColumnType("int");

                    b.Property<int?>("SubjectId")
                        .HasColumnType("int");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal?>("TargetScore10")
                        .HasColumnType("decimal(4, 2)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserSubjectId")
                        .HasColumnType("bigint");

                    b.ToTable((string)null);

                    b.ToView("vw_SubjectGradeSummary", (string)null);
                });

            modelBuilder.Entity("StudyHub.DAL.Entities.VwTermGradeSummary", b =>
                {
                    b.Property<long>("AcademicTermId")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("CurrentAverage10")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<int?>("SubjectsWithGrades")
                        .HasColumnType("int");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.ToTable((string)null);

                    b.ToView("vw_TermGradeSummary", (string)null);
                });

            modelBuilder.Entity("StudyHub.DAL.Entities.AcademicTerm", b =>
                {
                    b.HasOne("StudyHub.DAL.Entities.User", "User")
                        .WithMany("AcademicTerms")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_AcademicTerms_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StudyHub.DAL.Entities.ActivityEvent", b =>
                {
                    b.HasOne("StudyHub.DAL.Entities.User", "User")
                        .WithMany("ActivityEvents")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_ActivityEvents_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StudyHub.DAL.Entities.AuditLog", b =>
                {
                    b.HasOne("StudyHub.DAL.Entities.User", "ActorUser")
                        .WithMany("AuditLogs")
                        .HasForeignKey("ActorUserId")
                        .HasConstraintName("FK_AuditLogs_Actor");

                    b.Navigation("ActorUser");
                });

            modelBuilder.Entity("StudyHub.DAL.Entities.ContentReport", b =>
                {
                    b.HasOne("StudyHub.DAL.Entities.FlashcardDeck", "Deck")
                        .WithMany("ContentReports")
                        .HasForeignKey("DeckId")
                        .HasConstraintName("FK_ContentReports_Deck");

                    b.HasOne("StudyHub.DAL.Entities.Document", "Document")
                        .WithMany("ContentReports")
                        .HasForeignKey("DocumentId")
                        .HasConstraintName("FK_ContentReports_Document");

                    b.HasOne("StudyHub.DAL.Entities.GroupPost", "GroupPost")
                        .WithMany("ContentReports")
                        .HasForeignKey("GroupPostId")
                        .HasConstraintName("FK_ContentReports_Post");

                    b.HasOne("StudyHub.DAL.Entities.Note", "Note")
                        .WithMany("ContentReports")
                        .HasForeignKey("NoteId")
                        .HasConstraintName("FK_ContentReports_Note");

                    b.HasOne("StudyHub.DAL.Entities.User", "ReporterUser")
                        .WithMany("ContentReportReporterUsers")
                        .HasForeignKey("ReporterUserId")
                        .IsRequired()
                        .HasConstraintName("FK_ContentReports_Reporter");

                    b.HasOne("StudyHub.DAL.Entities.User", "ResolvedByUser")
                        .WithMany("ContentReportResolvedByUsers")
                        .HasForeignKey("ResolvedByUserId")
                        .HasConstraintName("FK_ContentReports_Resolver");

                    b.Navigation("Deck");

                    b.Navigation("Document");

                    b.Navigation("GroupPost");

                    b.Navigation("Note");

                    b.Navigation("ReporterUser");

                    b.Navigation("ResolvedByUser");
                });

            modelBuilder.Entity("StudyHub.DAL.Entities.Deadline", b =>
                {
                    b.HasOne("StudyHub.DAL.Entities.User", "User")
                        .WithMany("Deadlines")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Deadlines_User");

                    b.HasOne("StudyHub.DAL.Entities.UserSubject", "UserSubject")
                        .WithMany("Deadlines")
                        .HasForeignKey("UserSubjectId", "UserId")
                        .HasPrincipalKey("UserSubjectId", "UserId")
                        .HasConstraintName("FK_Deadlines_SubjectOwner");

                    b.Navigation("User");

                    b.Navigation("UserSubject");
                });

            modelBuilder.Entity("StudyHub.DAL.Entities.Document", b =>
                {
                    b.HasOne("StudyHub.DAL.Entities.User", "OwnerUser")
                        .WithMany("Documents")
                        .HasForeignKey("OwnerUserId")
                        .IsRequired()
                        .HasConstraintName("FK_Documents_User");

                    b.HasOne("StudyHub.DAL.Entities.StudyGroup", "StudyGroup")
                        .WithMany("Documents")
                        .HasForeignKey("StudyGroupId")
                        .HasConstraintName("FK_Documents_Group");

                    b.HasOne("StudyHub.DAL.Entities.UserSubject", "UserSubject")
                        .WithMany("Documents")
                        .HasForeignKey("UserSubjectId", "OwnerUserId")
                        .HasPrincipalKey("UserSubjectId", "UserId")
                        .HasConstraintName("FK_Documents_SubjectOwner");

                    b.Navigation("OwnerUser");

                    b.Navigation("StudyGroup");

                    b.Navigation("UserSubject");
                });

            modelBuilder.Entity("StudyHub.DAL.Entities.DocumentBookmark", b =>
                {
                    b.HasOne("StudyHub.DAL.Entities.Document", "Document")
                        .WithMany("DocumentBookmarks")
                        .HasForeignKey("DocumentId")
                        .IsRequired()
                        .HasConstraintName("FK_DocumentBookmarks_Document");

                    b.HasOne("StudyHub.DAL.Entities.User", "User")
                        .WithMany("DocumentBookmarks")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_DocumentBookmarks_User");

                    b.Navigation("Document");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StudyHub.DAL.Entities.ExternalLogin", b =>
                {
                    b.HasOne("StudyHub.DAL.Entities.User", "User")
                        .WithMany("ExternalLogins")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_ExternalLogins_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StudyHub.DAL.Entities.Flashcard", b =>
                {
                    b.HasOne("StudyHub.DAL.Entities.FlashcardDeck", "Deck")
                        .WithMany("Flashcards")
                        .HasForeignKey("DeckId")
                        .IsRequired()
                        .HasConstraintName("FK_Flashcards_Deck");

                    b.Navigation("Deck");
                });

            modelBuilder.Entity("StudyHub.DAL.Entities.FlashcardDeck", b =>
                {
                    b.HasOne("StudyHub.DAL.Entities.User", "OwnerUser")
                        .WithMany("FlashcardDecks")
                        .HasForeignKey("OwnerUserId")
                        .IsRequired()
                        .HasConstraintName("FK_FlashcardDecks_User");

                    b.HasOne("StudyHub.DAL.Entities.StudyGroup", "StudyGroup")
                        .WithMany("FlashcardDecks")
                        .HasForeignKey("StudyGroupId")
                        .HasConstraintName("FK_FlashcardDecks_Group");

                    b.HasOne("StudyHub.DAL.Entities.UserSubject", "UserSubject")
                        .WithMany("FlashcardDecks")
                        .HasForeignKey("UserSubjectId", "OwnerUserId")
                        .HasPrincipalKey("UserSubjectId", "UserId")
                        .HasConstraintName("FK_FlashcardDecks_SubjectOwner");

                    b.Navigation("OwnerUser");

                    b.Navigation("StudyGroup");

                    b.Navigation("UserSubject");
                });

            modelBuilder.Entity("StudyHub.DAL.Entities.FlashcardProgress", b =>
                {
                    b.HasOne("StudyHub.DAL.Entities.Flashcard", "Flashcard")
                        .WithMany("FlashcardProgresses")
                        .HasForeignKey("FlashcardId")
                        .IsRequired()
                        .HasConstraintName("FK_FlashcardProgress_Card");

                    b.HasOne("StudyHub.DAL.Entities.User", "User")
                        .WithMany("FlashcardProgresses")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_FlashcardProgress_User");

                    b.Navigation("Flashcard");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StudyHub.DAL.Entities.FlashcardReview", b =>
                {
                    b.HasOne("StudyHub.DAL.Entities.FlashcardProgress", "FlashcardProgress")
                        .WithMany("FlashcardReviews")
                        .HasForeignKey("UserId", "FlashcardId")
                        .IsRequired()
                        .HasConstraintName("FK_FlashcardReviews_Progress");

                    b.Navigation("FlashcardProgress");
                });

            modelBuilder.Entity("StudyHub.DAL.Entities.Goal", b =>
                {
                    b.HasOne("StudyHub.DAL.Entities.User", "User")
                        .WithMany("Goals")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Goals_User");

                    b.HasOne("StudyHub.DAL.Entities.UserSubject", "UserSubject")
                        .WithMany("Goals")
                        .HasForeignKey("UserSubjectId", "UserId")
                        .HasPrincipalKey("UserSubjectId", "UserId")
                        .HasConstraintName("FK_Goals_SubjectOwner");

                    b.Navigation("User");

                    b.Navigation("UserSubject");
                });

            modelBuilder.Entity("StudyHub.DAL.Entities.GradeEntry", b =>
                {
                    b.HasOne("StudyHub.DAL.Entities.UserSubject", "UserSubject")
                        .WithMany("GradeEntries")
                        .HasForeignKey("UserSubjectId")
                        .IsRequired()
                        .HasConstraintName("FK_GradeEntries_Subject");

                    b.Navigation("UserSubject");
                });

            modelBuilder.Entity("StudyHub.DAL.Entities.GroupInvite", b =>
                {
                    b.HasOne("StudyHub.DAL.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .IsRequired()
                        .HasConstraintName("FK_GroupInvites_Creator");

                    b.HasOne("StudyHub.DAL.Entities.StudyGroup", "StudyGroup")
                        .WithMany("GroupInvites")
                        .HasForeignKey("StudyGroupId")
                        .IsRequired()
                        .HasConstraintName("FK_GroupInvites_Group");

                    b.Navigation("CreatedByUser");

                    b.Navigation("StudyGroup");
                });

            modelBuilder.Entity("StudyHub.DAL.Entities.GroupMember", b =>
                {
                    b.HasOne("StudyHub.DAL.Entities.StudyGroup", "StudyGroup")
                        .WithMany("GroupMembers")
                        .HasForeignKey("StudyGroupId")
                        .IsRequired()
                        .HasConstraintName("FK_GroupMembers_Group");

                    b.HasOne("StudyHub.DAL.Entities.User", "User")
                        .WithMany("GroupMembers")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_GroupMembers_User");

                    b.Navigation("StudyGroup");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StudyHub.DAL.Entities.GroupPost", b =>
                {
                    b.HasOne("StudyHub.DAL.Entities.GroupMember", "GroupMember")
                        .WithMany("GroupPosts")
                        .HasForeignKey("StudyGroupId", "AuthorUserId")
                        .IsRequired()
                        .HasConstraintName("FK_GroupPosts_Member");

                    b.Navigation("GroupMember");
                });

            modelBuilder.Entity("StudyHub.DAL.Entities.Note", b =>
                {
                    b.HasOne("StudyHub.DAL.Entities.User", "OwnerUser")
                        .WithMany("Notes")
                        .HasForeignKey("OwnerUserId")
                        .IsRequired()
                        .HasConstraintName("FK_Notes_User");

                    b.HasOne("StudyHub.DAL.Entities.StudyGroup", "StudyGroup")
                        .WithMany("Notes")
                        .HasForeignKey("StudyGroupId")
                        .HasConstraintName("FK_Notes_Group");

                    b.HasOne("StudyHub.DAL.Entities.UserSubject", "UserSubject")
                        .WithMany("Notes")
                        .HasForeignKey("UserSubjectId", "OwnerUserId")
                        .HasPrincipalKey("UserSubjectId", "UserId")
                        .HasConstraintName("FK_Notes_SubjectOwner");

                    b.Navigation("OwnerUser");

                    b.Navigation("StudyGroup");

                    b.Navigation("UserSubject");
                });

            modelBuilder.Entity("StudyHub.DAL.Entities.Reminder", b =>
                {
                    b.HasOne("StudyHub.DAL.Entities.User", "User")
                        .WithMany("Reminders")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Reminders_User");

                    b.HasOne("StudyHub.DAL.Entities.Deadline", "Deadline")
                        .WithMany("Reminders")
                        .HasForeignKey("DeadlineId", "UserId")
                        .HasPrincipalKey("DeadlineId", "UserId")
                        .HasConstraintName("FK_Reminders_DeadlineOwner");

                    b.HasOne("StudyHub.DAL.Entities.ScheduleEvent", "ScheduleEvent")
                        .WithMany("Reminders")
                        .HasForeignKey("ScheduleEventId", "UserId")
                        .HasPrincipalKey("ScheduleEventId", "UserId")
                        .HasConstraintName("FK_Reminders_EventOwner");

                    b.Navigation("Deadline");

                    b.Navigation("ScheduleEvent");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StudyHub.DAL.Entities.ScheduleEvent", b =>
                {
                    b.HasOne("StudyHub.DAL.Entities.User", "User")
                        .WithMany("ScheduleEvents")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_ScheduleEvents_User");

                    b.HasOne("StudyHub.DAL.Entities.UserSubject", "UserSubject")
                        .WithMany("ScheduleEvents")
                        .HasForeignKey("UserSubjectId", "UserId")
                        .HasPrincipalKey("UserSubjectId", "UserId")
                        .HasConstraintName("FK_ScheduleEvents_SubjectOwner");

                    b.Navigation("User");

                    b.Navigation("UserSubject");
                });

            modelBuilder.Entity("StudyHub.DAL.Entities.ScheduleException", b =>
                {
                    b.HasOne("StudyHub.DAL.Entities.ScheduleEvent", "ScheduleEvent")
                        .WithMany("ScheduleExceptions")
                        .HasForeignKey("ScheduleEventId")
                        .IsRequired()
                        .HasConstraintName("FK_ScheduleExceptions_Event");

                    b.Navigation("ScheduleEvent");
                });

            modelBuilder.Entity("StudyHub.DAL.Entities.StudyGroup", b =>
                {
                    b.HasOne("StudyHub.DAL.Entities.User", "OwnerUser")
                        .WithMany("StudyGroups")
                        .HasForeignKey("OwnerUserId")
                        .IsRequired()
                        .HasConstraintName("FK_StudyGroups_Owner");

                    b.HasOne("StudyHub.DAL.Entities.Subject", "Subject")
                        .WithMany("StudyGroups")
                        .HasForeignKey("SubjectId")
                        .HasConstraintName("FK_StudyGroups_Subject");

                    b.Navigation("OwnerUser");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("StudyHub.DAL.Entities.StudySession", b =>
                {
                    b.HasOne("StudyHub.DAL.Entities.User", "User")
                        .WithOne("StudySession")
                        .HasForeignKey("StudyHub.DAL.Entities.StudySession", "UserId")
                        .IsRequired()
                        .HasConstraintName("FK_StudySessions_User");

                    b.HasOne("StudyHub.DAL.Entities.UserSubject", "UserSubject")
                        .WithMany("StudySessions")
                        .HasForeignKey("UserSubjectId", "UserId")
                        .HasPrincipalKey("UserSubjectId", "UserId")
                        .HasConstraintName("FK_StudySessions_SubjectOwner");

                    b.Navigation("User");

                    b.Navigation("UserSubject");
                });

            modelBuilder.Entity("StudyHub.DAL.Entities.SystemSetting", b =>
                {
                    b.HasOne("StudyHub.DAL.Entities.User", "UpdatedByUser")
                        .WithMany("SystemSettings")
                        .HasForeignKey("UpdatedByUserId")
                        .HasConstraintName("FK_SystemSettings_User");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("StudyHub.DAL.Entities.UserSetting", b =>
                {
                    b.HasOne("StudyHub.DAL.Entities.User", "User")
                        .WithOne("UserSetting")
                        .HasForeignKey("StudyHub.DAL.Entities.UserSetting", "UserId")
                        .IsRequired()
                        .HasConstraintName("FK_UserSettings_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StudyHub.DAL.Entities.UserSubject", b =>
                {
                    b.HasOne("StudyHub.DAL.Entities.Subject", "Subject")
                        .WithMany("UserSubjects")
                        .HasForeignKey("SubjectId")
                        .HasConstraintName("FK_UserSubjects_Subject");

                    b.HasOne("StudyHub.DAL.Entities.User", "User")
                        .WithMany("UserSubjects")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_UserSubjects_User");

                    b.HasOne("StudyHub.DAL.Entities.AcademicTerm", "AcademicTerm")
                        .WithMany("UserSubjects")
                        .HasForeignKey("AcademicTermId", "UserId")
                        .HasPrincipalKey("AcademicTermId", "UserId")
                        .IsRequired()
                        .HasConstraintName("FK_UserSubjects_TermOwner");

                    b.Navigation("AcademicTerm");

                    b.Navigation("Subject");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StudyHub.DAL.Entities.AcademicTerm", b =>
                {
                    b.Navigation("UserSubjects");
                });

            modelBuilder.Entity("StudyHub.DAL.Entities.Deadline", b =>
                {
                    b.Navigation("Reminders");
                });

            modelBuilder.Entity("StudyHub.DAL.Entities.Document", b =>
                {
                    b.Navigation("ContentReports");

                    b.Navigation("DocumentBookmarks");
                });

            modelBuilder.Entity("StudyHub.DAL.Entities.Flashcard", b =>
                {
                    b.Navigation("FlashcardProgresses");
                });

            modelBuilder.Entity("StudyHub.DAL.Entities.FlashcardDeck", b =>
                {
                    b.Navigation("ContentReports");

                    b.Navigation("Flashcards");
                });

            modelBuilder.Entity("StudyHub.DAL.Entities.FlashcardProgress", b =>
                {
                    b.Navigation("FlashcardReviews");
                });

            modelBuilder.Entity("StudyHub.DAL.Entities.GroupMember", b =>
                {
                    b.Navigation("GroupPosts");
                });

            modelBuilder.Entity("StudyHub.DAL.Entities.GroupPost", b =>
                {
                    b.Navigation("ContentReports");
                });

            modelBuilder.Entity("StudyHub.DAL.Entities.Note", b =>
                {
                    b.Navigation("ContentReports");
                });

            modelBuilder.Entity("StudyHub.DAL.Entities.ScheduleEvent", b =>
                {
                    b.Navigation("Reminders");

                    b.Navigation("ScheduleExceptions");
                });

            modelBuilder.Entity("StudyHub.DAL.Entities.StudyGroup", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("FlashcardDecks");

                    b.Navigation("GroupInvites");

                    b.Navigation("GroupMembers");

                    b.Navigation("Notes");
                });

            modelBuilder.Entity("StudyHub.DAL.Entities.Subject", b =>
                {
                    b.Navigation("StudyGroups");

                    b.Navigation("UserSubjects");
                });

            modelBuilder.Entity("StudyHub.DAL.Entities.User", b =>
                {
                    b.Navigation("AcademicTerms");

                    b.Navigation("ActivityEvents");

                    b.Navigation("AuditLogs");

                    b.Navigation("ContentReportReporterUsers");

                    b.Navigation("ContentReportResolvedByUsers");

                    b.Navigation("Deadlines");

                    b.Navigation("DocumentBookmarks");

                    b.Navigation("Documents");

                    b.Navigation("ExternalLogins");

                    b.Navigation("FlashcardDecks");

                    b.Navigation("FlashcardProgresses");

                    b.Navigation("Goals");

                    b.Navigation("GroupMembers");

                    b.Navigation("Notes");

                    b.Navigation("Reminders");

                    b.Navigation("ScheduleEvents");

                    b.Navigation("StudyGroups");

                    b.Navigation("StudySession");

                    b.Navigation("SystemSettings");

                    b.Navigation("UserSetting");

                    b.Navigation("UserSubjects");
                });

            modelBuilder.Entity("StudyHub.DAL.Entities.UserSubject", b =>
                {
                    b.Navigation("Deadlines");

                    b.Navigation("Documents");

                    b.Navigation("FlashcardDecks");

                    b.Navigation("Goals");

                    b.Navigation("GradeEntries");

                    b.Navigation("Notes");

                    b.Navigation("ScheduleEvents");

                    b.Navigation("StudySessions");
                });
#pragma warning restore 612, 618
        }
    }
}
